### ISSUE TITLE
Wall Pattern Broken?

### ISSUE THREAD

**Issue by jprisant** [ostat/gridfinity_extended_openscad#23] opened 2024-05-07 16:01 UTC
Is the wall pattern functionality broken?

When I try to use wall pattern in any of the primary .scad files, it only seems to work for one wall?

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/6282841/6ae21ab7-df0c-42ab-87cb-08772417d599)

**Comment by ostat** [comment] 2024-05-08 14:09
I am not able to reproduce locally. I can see in the image you shared there are a bunch of errors though.

Would you mind double checking you have the latest, just in case its already fixed.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/a45bb5c2-c0d1-47a6-af66-f507d3868583)

**Comment by bbrendon** [comment] 2024-05-17 23:22
I tried this on the web version and couldn't get the wallpattern working on more than one side. 

https://seasick.github.io/openscad-web-gui/?https%3A%2F%2Fraw.githubusercontent.com%2Fostat%2Fgridfinity_extended_openscad%2Fmain%2Fcombined%2Fgridfinity_basic_cup.scad

**Comment by bbrendon** [comment] 2024-05-17 23:38
It worked after I cloned the repo and opened the cup file. 
There should be some instructions on how to use this. It took me awhile to figure out you have to download everything and not just the cup file.

**Comment by ostat** [comment] 2024-05-18 01:22
You are right the online version is broken, I will get that fixed. Thanks for letting me know.
I will also update the doco to make it easier to get up and running.

**Comment by ostat** [comment] 2024-06-10 07:51
There is some strange caching happening with the seasick openscad-web-gui.

You can use the online version on Maker World which is now supported
https://makerworld.com/en/models/481168

**Comment by jprisant** [comment] 2024-06-26 14:57
> I am not able to reproduce locally. I can see in the image you shared there are a bunch of errors though.
> 
> Would you mind double checking you have the latest, just in case its already fixed.

I just saw this response! Sorry about the ridiculously late response. 

I redownloaded the repo today... I opened in OpenSCAD Dev version 2024.04.29 (git 97184930d) ... but still have the problem with the wall pattern... and now vertical separators don't seem to work either. 

![2024-06-26_07-45-59](https://github.com/ostat/gridfinity_extended_openscad/assets/6282841/86d3d4ab-8146-4df2-b28e-1b51a6de0548)

I also extracted to a separate folder to open in OpenSCAD stable and experienced different issues.

I assume the problem is on my end, but I have no idea what else to try.

**Comment by jprisant** [comment] 2024-07-26 05:53
I just downloaded the newest openscad nightly and a copy of the gridfinity_extended repo, but I am still experiencing all these errors when trying to generate wall patterns
![image](https://github.com/user-attachments/assets/27946119-9c2a-47a0-a339-6358f2eb369e)

When I try to use the makerworld builder, the divider pattern  option doesn't work
![image](https://github.com/user-attachments/assets/abbb3a1f-666c-4997-b37c-f28cf4903b4f)

**Comment by ostat** [comment] 2024-07-26 09:07
> I just downloaded the newest openscad nightly and a copy of the gridfinity_extended repo, but I am still experiencing all these errors when trying to generate wall patterns
> 
> ![image](https://github.com/user-attachments/assets/27946119-9c2a-47a0-a339-6358f2eb369e)
> 
> 
> 
> When I try to use the makerworld builder, the divider pattern  option doesn't work
> 
> ![image](https://github.com/user-attachments/assets/abbb3a1f-666c-4997-b37c-f28cf4903b4f)
> 
> 

I have tried to reproduce the issue but have been unsuccessful. 
Could you please try download the repo as a zip. Unzip it to a new folder and run it from there? See how it goes.

**Comment by ostat** [comment] 2024-07-26 10:34
The divider pattern seems to only work on the non custom walls. 
Use the `Vertical chambers` option not the `Vertical chamber config`. I will look in to why that is not supported.

![image](https://github.com/user-attachments/assets/d9860f52-a14d-45f7-8471-bca6c33fe742)

**Comment by ostat** [comment] 2024-07-27 23:40
The wall pattern divider walls now works on the custom configured walls. I have confirmed it works both locally and on makerworld.

![image](https://github.com/user-attachments/assets/e431e039-0ac9-487c-b297-1060b6b4f25b)

![image](https://github.com/user-attachments/assets/f2df1c7b-14dd-437e-8305-f6cddc7aa62d)

**Comment by ostat** [comment] 2024-08-06 11:33
closed as fixed, @jprisant let me know if you still have issues we can re open

**Closed by ostat** 2024-08-06 11:33 UTC
Labels: bug
